create extension if not exists pgcrypto;

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique check (char_length(username) between 2 and 32),
  created_at timestamptz not null default now()
);

create or replace function public.create_profile_for_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  base_name text;
begin
  base_name := lower(regexp_replace(
    coalesce(new.raw_user_meta_data ->> 'username', split_part(coalesce(new.email, 'citizen'), '@', 1)),
    '[^a-zA-Z0-9_]+', '', 'g'
  ));
  base_name := left(coalesce(nullif(base_name, ''), 'citizen'), 23) || '_' || left(new.id::text, 8);
  insert into public.profiles (user_id, username)
  values (new.id, base_name)
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists create_profile_after_signup on auth.users;
create trigger create_profile_after_signup
after insert on auth.users
for each row execute procedure public.create_profile_for_user();

create table if not exists public.videos (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 120),
  state text not null check (char_length(state) between 1 and 60),
  city text check (city is null or char_length(city) <= 60),
  description text check (description is null or char_length(description) <= 500),
  video_url text not null check (
    char_length(video_url) <= 2048 and (
      video_url ~* '^https://(www\.)?(youtube\.com|youtube-nocookie\.com|youtu\.be|vimeo\.com|player\.vimeo\.com|dailymotion\.com|dai\.ly)/'
      or video_url like 'https://luzjxwwjhxysxwhkzydd.supabase.co/storage/v1/object/public/citizen-videos/%'
    )
  ),
  created_at timestamptz not null default now()
);

alter table public.videos add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.videos enable row level security;
drop policy if exists "Anyone can view videos" on public.videos;
drop policy if exists "Anyone can upload video records" on public.videos;
drop policy if exists "Authenticated users can upload validated video records" on public.videos;
drop policy if exists "Public videos are readable" on public.videos;
drop policy if exists "Authenticated creators publish videos" on public.videos;
drop policy if exists "Creators update their videos" on public.videos;
drop policy if exists "Creators delete their videos" on public.videos;
create policy "Public videos are readable"
on public.videos for select to anon, authenticated using (true);
create policy "Authenticated creators publish videos"
on public.videos for insert to authenticated
with check (
  user_id = (select auth.uid())
  and char_length(title) between 1 and 120
  and char_length(state) between 1 and 60
  and (city is null or char_length(city) <= 60)
  and (description is null or char_length(description) <= 500)
);
create policy "Creators update their videos"
on public.videos for update to authenticated
using (user_id = (select auth.uid()))
with check (user_id = (select auth.uid()));
create policy "Creators delete their videos"
on public.videos for delete to authenticated
using (user_id = (select auth.uid()));

create table if not exists public.video_likes (
  video_id bigint not null references public.videos(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (video_id, user_id)
);
alter table public.video_likes enable row level security;
drop policy if exists "Anyone can view video likes" on public.video_likes;
drop policy if exists "Users add their own video likes" on public.video_likes;
drop policy if exists "Users remove their own video likes" on public.video_likes;
create policy "Anyone can view video likes"
on public.video_likes for select to anon, authenticated using (true);
create policy "Users add their own video likes"
on public.video_likes for insert to authenticated
with check (user_id = (select auth.uid()));
create policy "Users remove their own video likes"
on public.video_likes for delete to authenticated
using (user_id = (select auth.uid()));

create table if not exists public.video_comments (
  id bigint generated by default as identity primary key,
  video_id bigint not null references public.videos(id) on delete cascade,
  user_id uuid not null references public.profiles(user_id) on delete cascade,
  body text not null check (char_length(body) between 1 and 1000),
  created_at timestamptz not null default now()
);
create index if not exists video_comments_video_created_idx on public.video_comments (video_id, created_at);
alter table public.video_comments enable row level security;
drop policy if exists "Anyone can read video comments" on public.video_comments;
drop policy if exists "Signed-in users comment on videos" on public.video_comments;
drop policy if exists "Users delete their own comments" on public.video_comments;
create policy "Anyone can read video comments"
on public.video_comments for select to anon, authenticated using (true);
create policy "Signed-in users comment on videos"
on public.video_comments for insert to authenticated
with check (user_id = (select auth.uid()) and char_length(body) between 1 and 1000);
create policy "Users delete their own comments"
on public.video_comments for delete to authenticated
using (user_id = (select auth.uid()));

create table if not exists public.video_saves (
  video_id bigint not null references public.videos(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (video_id, user_id)
);
alter table public.video_saves enable row level security;
drop policy if exists "Users read their saved videos" on public.video_saves;
drop policy if exists "Users save videos" on public.video_saves;
drop policy if exists "Users unsave videos" on public.video_saves;
create policy "Users read their saved videos"
on public.video_saves for select to authenticated
using (user_id = (select auth.uid()));
create policy "Users save videos"
on public.video_saves for insert to authenticated
with check (user_id = (select auth.uid()));
create policy "Users unsave videos"
on public.video_saves for delete to authenticated
using (user_id = (select auth.uid()));

create table if not exists public.creator_follows (
  creator_id uuid not null references public.profiles(user_id) on delete cascade,
  follower_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (creator_id, follower_id),
  check (creator_id <> follower_id)
);
alter table public.creator_follows enable row level security;
drop policy if exists "Users read their creator follows" on public.creator_follows;
drop policy if exists "Users follow creators" on public.creator_follows;
drop policy if exists "Users unfollow creators" on public.creator_follows;
create policy "Users read their creator follows"
on public.creator_follows for select to authenticated
using (follower_id = (select auth.uid()));
create policy "Users follow creators"
on public.creator_follows for insert to authenticated
with check (follower_id = (select auth.uid()));
create policy "Users unfollow creators"
on public.creator_follows for delete to authenticated
using (follower_id = (select auth.uid()));

alter table public.profiles enable row level security;
drop policy if exists "Public creator profiles are readable" on public.profiles;
drop policy if exists "Users edit their own profile" on public.profiles;
create policy "Public creator profiles are readable"
on public.profiles for select to anon, authenticated using (true);
create policy "Users edit their own profile"
on public.profiles for update to authenticated
using (user_id = (select auth.uid()))
with check (user_id = (select auth.uid()));

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('citizen-videos', 'citizen-videos', true, 104857600, array['video/mp4', 'video/webm', 'video/quicktime'])
on conflict (id) do update
set public = true, file_size_limit = 104857600,
    allowed_mime_types = array['video/mp4', 'video/webm', 'video/quicktime'];
drop policy if exists "Public can view community videos" on storage.objects;
drop policy if exists "Signed-in creators upload their own videos" on storage.objects;
drop policy if exists "Creators delete their own videos" on storage.objects;
create policy "Public can view community videos"
on storage.objects for select to anon, authenticated
using (bucket_id = 'citizen-videos');
create policy "Signed-in creators upload their own videos"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'citizen-videos'
  and (storage.foldername(name))[1] = (select auth.uid())::text
  and lower(storage.extension(name)) in ('mp4', 'webm', 'mov')
);
create policy "Creators delete their own videos"
on storage.objects for delete to authenticated
using (
  bucket_id = 'citizen-videos'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);
